### ISSUE TITLE
Need some kind of rate-limit queue for Instagram requests

### ISSUE THREAD

**Issue by turt2live** [turt2live/matrix-appservice-instagram#1]
Requests can pile up quickly and cause the bridge to exceed the rate limit very quickly. Some kind of process queue should be put in place to ensure that we don't exceed the limit (and continue to make requests).

Things like user profile updates and media polling should be added to a queue that is processed as time goes on, trying to avoid the rate limit. If the rate limit is reached, a cooldown period before retrying the queue should be enabled.

**Comment by lukebarnard1** [comment]
AFAIK matrix-js-sdk should look after rate limiting for you. You could also disable rate limiting from the AS registration file :innocent:

**Comment by turt2live** [comment]
This is more for the Instagram queuing. For users that don't authenticate with the bridge, we have to poll for updates. As user count increases, the number of requests also goes up. With the current code I was also hitting the sandbox rate limit (500/hr) easily.
