### ISSUE TITLE
Integrate Instagram Direct API for bridging chats to Matrix too

### ISSUE THREAD

**Issue by MurzNN** [turt2live/matrix-appservice-instagram#57]
Here https://github.com/turt2live/matrix-wishlist/issues/254 is my feature request for bridge Instagram Direct chats into Matrix. Seems there are already implemented base API for Instagram (Media part) on Node.JS and appservice part on Matrix side.

Maybe will be easier to add Instagram Direct API here, instead of separate project?

**Comment by turt2live** [comment]
This bridge will not be supporting direct chats, sorry.

**Comment by kiliankoe** [comment]
That's a shame, but understandable. I came here hoping for this.
